# Generated by Django 5.0.2 on 2024-04-08 04:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slno', models.IntegerField()),
                ('pname', models.CharField(max_length=40)),
                ('rate', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('total', models.IntegerField()),
                ('userid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50)),
                ('ph', models.CharField(max_length=50)),
                ('feed', models.CharField(max_length=550)),
            ],
        ),
        migrations.CreateModel(
            name='onlinemaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesno', models.IntegerField()),
                ('salesdate', models.DateField(default=datetime.date.today)),
                ('userid', models.IntegerField()),
                ('uname', models.CharField(max_length=30)),
                ('shipment', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=10)),
                ('cardno', models.CharField(max_length=40)),
                ('total', models.IntegerField()),
                ('status', models.CharField(default='New Order', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='onlinesub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesno', models.IntegerField()),
                ('slno', models.IntegerField()),
                ('pname', models.CharField(max_length=40)),
                ('rate', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prid', models.CharField(max_length=30)),
                ('prname', models.CharField(max_length=30)),
                ('price', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('photo', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='userreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('rights', models.CharField(default='user', max_length=255)),
            ],
        ),
    ]
